name: Formatting & Linting Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js for React client
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      # Install dependencies for React client
      - name: Install Node.js dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps

      # Run ESLint for React client
      - name: Run ESLint
        working-directory: ./client
        run: npm run lint:check

      # Run Prettier for React client
      - name: Run Prettier
        working-directory: ./client
        run: npm run fmt:check

      # Set up Python for Django server
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install pipenv for Django server
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      # Install dependencies for Django server
      - name: Install Python dependencies
        working-directory: ./server
        run: |
          pipenv install --dev

      # Run Ruff for linting Django server
      - name: Run Ruff Lint
        working-directory: ./server
        run: |
          pipenv run ruff check

      # Run Ruff for formatting Django server
      - name: Run Ruff Format
        working-directory: ./server
        run: |
          pipenv run ruff format
